// Code generated by internal/generate/tagstests/main.go; DO NOT EDIT.

package cleanrooms_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/blampe/patches/mirrors/aws/v5/internal/acctest/statecheck"
	tfcleanrooms "github.com/blampe/patches/mirrors/aws/v5/internal/service/cleanrooms"
)

func expectFullResourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tfcleanrooms.ServicePackage(context.Background()), resourceAddress, knownValue)
}
