// Code generated by internal/generate/tagstests/main.go; DO NOT EDIT.

package iam_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/blampe/patches/mirrors/aws/v5/internal/acctest/statecheck"
	tfiam "github.com/blampe/patches/mirrors/aws/v5/internal/service/iam"
)

func expectFullResourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tfiam.ServicePackage(context.Background()), resourceAddress, knownValue)
}

func expectFullDataSourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullDataSourceTags(tfiam.ServicePackage(context.Background()), resourceAddress, knownValue)
}
