// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/generate/tagstests/main.go; DO NOT EDIT.

package drs_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/blampe/patches/mirrors/aws/v6/internal/acctest/statecheck"
	tfdrs "github.com/blampe/patches/mirrors/aws/v6/internal/service/drs"
)

func expectFullResourceTags(ctx context.Context, resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tfdrs.ServicePackage(ctx), resourceAddress, knownValue)
}
